export const LOAD_ID_FROM_SERVER = 'LOAD_ID_FROM_SERVER';
export const LOAD_PRODUCTS_FROM_SERVER = 'LOAD_PRODUCTS_FROM_SERVER';
export const LOAD_USERS_FROM_SERVER = 'LOAD_USERS_FROM_SERVER';
export const LOAD_BRANDS_FROM_SERVER = 'LOAD_BRANDS_FROM_SERVER';

