export const LOAD_ID_FROM_SERVER = 'LOAD_ID_FROM_SERVER';
export const LOAD_PRODUCTS_FROM_SERVER = 'LOAD_PRODUCTS_FROM_SERVER';
export const LOAD_USERS_FROM_SERVER = 'LOAD_USERS_FROM_SERVER';
export const LOAD_BRANDS_FROM_SERVER = 'LOAD_BRANDS_FROM_SERVER';
export const LOAD_BRANDS_ALL_FROM_SERVER = "LOAD_BRANDS_ALL_FROM_SERVER"
export const LOAD_CATEGORIES_FROM_SERVER = "LOAD_CATEGORIES_FROM_SERVER"

export const FILTER_PRODUCTS_BRAND = 'FILTER_PRODUCTS_BRAND';
export const FILTER_CATEGORIES = 'FILTER_CATEGORIES';

